export const GET_HYDROPONICFARM_REQUEST="GET_HYDROPONICFARM_REQUEST";
export const GET_HYDROPONICFARM_SUCCESS="GET_HYDROPONICFARM_SUCCESS";
export const GET_HYDROPONICFARM_FAILURE="GET_HYDROPONICFARM_FAILURE";

export const GET_HYDOPONICPRODUCT_REQUEST="GET_HYDOPONICPRODUCT_REQUEST";
export const GET_HYDOPONICPRODUCT_SUCCESS="GET_HYDOPONICPRODUCT_SUCCESS";
export const GET_HYDOPONICPRODUCT_FAILURE="GET_HYDOPONICPRODUCT_FAILURE";

export const GET_AUTOMATINGFARM_REQUEST="GET_AUTOMATINGFARM_REQUEST";
export const GET_AUTOMATINGFARM_SUCCESS="GET_AUTOMATINGFARM_SUCCESS";
export const GET_AUTOMATINGFARM_FAILURE="GET_AUTOMATINGFARM_FAILURE";

export const GET_SELLINGDIRECTELY_REQUEST="GET_SELLINGDIRECTELY_REQUEST";
export const GET_SELLINGDIRECTELY_SUCCESS="GET_SELLINGDIRECTELY_SUCCESS";
export const GET_SELLINGDIRECTELY_FAILURE="GET_SELLINGDIRECTELY_FAILURE";

export const  ADD_TO_CART="ADD_TO_CAR"